### ISSUE TITLE
Appointment Notes- Intake Section

### ISSUE THREAD

**Issue by CaptainChaos24** [Snowdrama/ElementsTools#1]
Changing the Appt note portion "INTAKE" answer selection to:

-MT Sign OFF
-Sent

![image](https://github.com/Snowdrama/ElementsTools/assets/165099185/5d418d63-89e4-418a-b903-0b1393f56ef3)

**Comment by Snowdrama** [comment]
Fixed in this one, wrong branch but had other fixes
https://github.com/Snowdrama/ElementsTools/pull/7

**Comment by Snowdrama** [comment]
Side note here as of right now the fix was just to change "Needs Updating" to "MT Sign Off" and then "Current" doesn't output anything. Current is selected by default and no longer outputs "Intake: Current" but the option is still there because it's needed as an option for the radio button
